language: cpp
os: linux
dist: yakkety
sudo: required

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
install:
  - sudo perl devkitARMupdate.pl   
  - wget --no-check-certificate https://codeload.github.com/fincs/citro3d/zip/master -O /tmp/citro3d.zip
  - unzip /tmp/citro3d.zip
  - cd citro3d-master
  - make && sudo make install
  - cd ..
  - wget --no-check-certificate  https://raw.githubusercontent.com/libretro/RetroArch/master/ctr/tools/bannertool-linux
  - chmod 777 bannertool-linux
  - sudo mv bannertool-linux buildtools//3ds/bannertool-linux64
  - wget --no-check-certificate  https://raw.githubusercontent.com/libretro/RetroArch/master/ctr/tools/makerom-linux
  - chmod 777 makerom-linux
  - sudo cp makerom-linux /usr/bin/makerom
  - cd ..  
script:
  - cd NTRDBI
  - echo "Starting compilation"
  - echo "Compiling NTRDBI"
  - make
  - echo "Compilation ended"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp